### ISSUE TITLE
Missing Semantic Labels in the Provided DDD17 Dataset

### ISSUE THREAD

**Issue by ldkong1205** [uzh-rpg/ess#11]
Hi @SunZNing, @MessikommerNico, @danielgehrig18, thanks again for your work!

The pre-processed DDD17 dataset that you provided with this repository seems not complete. After downloading it with this link (https://download.ifi.uzh.ch/rpg/ESS/ddd17_seg.tar.gz), I found that the number of files in the `segmentation_masks` folders is not consistent with the EV-SegNet paper. 

For example, the `segmentation_masks` folder of `dir5` only contains one file named `segmentation_00003925.png`. Could you re-upload the complete dataset?

Thanks in advance for your help!

**Comment by hhhhzp** [comment]
Hi @ldkong1205,  I guess the valid split dir[1] from def get_split() is the test sequence in ddd17 and the train split is everything except dirs[1] and dirs[4] since the number of samples in each split is consistent with the EV-SegNet. Please let me know if it's true.

**Comment by MessikommerNico** [comment]
Hi,
I checked our data locally, and it is consistent with the data we provide (https://download.ifi.uzh.ch/rpg/ESS/ddd17_seg.tar.gz). As @hhhhzp pointed out, the training splits consist of samples from different dirs. Just this week. the authors of EV-SegNet replaced the download link for DDD17_Seg, which should work again. You can check there if the samples are the same.

**Comment by ldkong1205** [comment]
Hi @hhhhzp and @MessikommerNico, thanks a lot for your reply!

I can confirm that the provided data (https://download.ifi.uzh.ch/rpg/ESS/ddd17_seg.tar.gz) contains the same amount of data as the newly updated DDD17_Seg ([link](https://unizares-my.sharepoint.com/:f:/g/personal/acm_unizar_es/Eiz_9LWWOEJAmmtfiAXWS0QB5pzfHHaA5K-41HrMo2sVdQ?e=f3fhxM)) from the EV-SegNet authors.

The training sequences (15950) are:

| Seq | dir0 | dir3 | dir 4 | dir6 | dir7 |
|:-:|:-:|:-:|:-:|:-:|:-:| 
| # Frames | 5550 | 1320 | 6945 | 1140 | 995 |

The validation sequence (3890) is:
| Seq | dir1 | 
|:-:|:-:|
| # Frames | 3890 |

Thanks again for your help!
