### ISSUE TITLE
DSEC validation & test split

### ISSUE THREAD

**Issue by Candy-Crusher** [uzh-rpg/ess#12]
Thank you for your excellent work! I couldn't find a test script in the repository. I was wondering if you could confirm whether the validation and test sets are the same, specifically Zurich 13a, 14c, and 15a?

**Comment by MessikommerNico** [comment]
Apologies for the late response.

Yes, I can confirm that Zurich 13a, 14c, and 15a are the used test sequences, as also stated in Sec. 6 in our paper.
