### ISSUE TITLE
how to load dict model as .pt file ?

### ISSUE THREAD

**Issue by 5221029** [uzh-rpg/ess#13]
Hello, I downloaded some files (DDD17 UDA , DSEC UDA as .pt file) from you. The files are in the form of a dictionary. How can I convert this dictionary into the original model so that I can get output from it?

here is my code and error :
model= torch.load(r'C:\Users\ehnza\Downloads\DSEC_Semantic_UDA.pt', map_location=torch.device('cpu'))
model('x.jpeg')

Error : 
TypeError: 'dict' object is not callable

I know why this is happening, but I don't know how to convert it to the original file

**Comment by MessikommerNico** [comment]
Hi,
Apologies for the late response.
Please have a look at the following functions:

1. def load_pretrained_weights(self, models, model_list, checkpoint_file=None):
https://github.com/uzh-rpg/ess/blob/46bf1eed677d869c4733c89d2284e43ea27f97bd/utils/saver.py#L50

2. def load_model(path_to_model, return_task=False):
https://github.com/uzh-rpg/ess/blob/46bf1eed677d869c4733c89d2284e43ea27f97bd/e2vid/utils/loading_utils.py#L5

Make sure that you load the trained task decoder as well as the frozen E2VID weights.
