### ISSUE TITLE
Supervised only with events

### ISSUE THREAD

**Issue by SchuckLee** [uzh-rpg/ess#14]
Hello, I would like to know how to set up supervised learning on ess using only events? I have set train_on_event_labels: True and model_name: 'ess_supervised', but I still use frame for training...

**Comment by MessikommerNico** [comment]
Hi,
If you set the `model_name == 'ess_supervised'`, it uses [ESSSupervisedModel](https://github.com/uzh-rpg/ess/blob/46bf1eed677d869c4733c89d2284e43ea27f97bd/training/ess_supervised_trainer.py#L21). This module should not use any frames for the training, see https://github.com/uzh-rpg/ess/blob/46bf1eed677d869c4733c89d2284e43ea27f97bd/training/ess_supervised_trainer.py#L111.
How do you notice that it still uses frames?

**Comment by SchuckLee** [comment]
While running the code, I noticed that the Cityscapes dataset needs to be loaded, and Line 36 in settings_DDD17.yaml:[https://github.com/uzh-rpg/ess/blob/46bf1eed677d869c4733c89d2284e43ea27f97bd/config/settings_DDD17.yaml#L36](url)
 `train_on_event_labels: False # True for ESS supervised (events labels + frames labels), False for ESS UDA` , which was confusing to me. Now it's resolved. Thank you for your reply!

**Comment by wzz-z** [comment]
> 在运行代码时，我注意到需要加载 Cityscapes 数据集，以及 settings_DDD17.yaml：[https://github.com/uzh-rpg/ess/blob/46bf1eed677d869c4733c89d2284e43ea27f97bd/config/settings_DDD17.yaml#L36](url) 中的第 36 行，这让我感到困惑。现在它已经解决了。谢谢你的回复！`train_on_event_labels: False # True for ESS supervised (events labels + frames labels), False for ESS UDA`

I encountered the same issue. I set `train_on_event_labels: False` and `model_name: “ess_supervised”`, but the error message still indicates an incorrect Cityscapes dataset path.
