### ISSUE TITLE
What type of format the dataset DDD17 should have?

### ISSUE THREAD

**Issue by liwr-hit** [uzh-rpg/ess#3]
Thank you for your work. May I ask What type of format the dataset DDD17 should have?

**Comment by MessikommerNico** [comment]
Hi
We have just included a download link for the preprocessed DDD17 dataset in the ReadMe file. For more information about the format, you can have a look at the example dataloader: https://github.com/uzh-rpg/ess/blob/main/datasets/extract_data_tools/example_loader_ddd17.py
