### ISSUE TITLE
A problem about load dataset

### ISSUE THREAD

**Issue by sherlie831** [uzh-rpg/ess#4]
Hi, I am trying to run ESS, may I ask which sequence of Cityspace is used for training? What is the format of the Cityspace dataset?

**Comment by sherlie831** [comment]
I have downloaded leftimg8bit and gtFine from the Cityspace website to solve the above problem.

But the following error occurred when I tried to run **train.py**:
`Loading model e2vid/pretrained/E2VID_lightweight.pth.tar... `
`Using TransposedConvLayer (fast, with checkerboard artefacts)`
`Using TransposedConvLayer (fast, with checkerboard artefacts)`
`Cityscapes num of batches:  371 62`
`Traceback (most recent call last):`
 ` File "/home/x/code/ESS/train.py", line 57, in <module>`
  `  main()`
`  File "/home/x/code/ESS/train.py", line 38, in main`
`    trainer = ESSModel(settings)`
`  File "/home/x/code/ESS/training/ess_trainer.py", line 22, in __init__`
`    super(ESSModel, self).__init__(settings)`
`  File "/home/x/code/ESS/training/base_trainer.py", line 29, in __init__`
`    self.createDataLoaders()`
`  File "/home/x/code/ESS/training/base_trainer.py", line 320, in createDataLoaders`
`    self.settings.fixed_duration_b)`
`  File "/home/x/code/ESS/training/base_trainer.py", line 173, in createDSECDataset`
`    fixed_duration=fixed_duration)`
`  File "/home/x/code/ESS/datasets/DSEC_events_loader.py", line 36, in DSECEvents`
`    augmentation=augmentation, fixed_duration=fixed_duration, resize=resize)`
`  File "/home/x/code/ESS/DSEC/dataset/provider.py", line 45, in __init__`
`    , resize=resize))`
`  File "/home/x/code/ESS/DSEC/dataset/sequence.py", line 109, in __init__`
`    assert img_left_dir.is_dir()`
`AssertionError`
`

I try to positioning error, I found in the **ESS/DSEC/dataset/sequence. py** files line 107：
`   if self.require_paired_data:`
`  img_dir = seq_path / 'images'`
`  img_left_dir = img_dir / 'left' / 'ev_inf'`
`   assert img_left_dir.is_dir()`

The code runs here to load images from **test/zurich_city_13_a/images**, and DSEC-Semantic does not have this folder, so what images are being loaded here?

**Comment by ldkong1205** [comment]
Hi @sherlie831, sorry to bother you! Have you solved this problem? What does `ev_inf` mean here?
