### ISSUE TITLE
Cityscapes dataset

### ISSUE THREAD

**Issue by cciprianmihai** [uzh-rpg/ess#5]
Hello.

I am kindly asking for some details regarding the **Cityscapes** dataset. 

- Which dataset to download? Because on the official website, there are multiple downloading links;
- How to organize it on the disk?

Thanks a lot!

**Comment by MessikommerNico** [comment]
Hi
We are using the PyTorch loader for the Cityscapes Dataset, which needs the root directory where `leftImg8bit` and `gtFine` is located.  For more information, check out the PyTorch documentation:
https://pytorch.org/vision/main/generated/torchvision.datasets.Cityscapes.html

**Comment by cciprianmihai** [comment]
Thanks. Is working now.
